Traceback (most recent call last):
  File "b:\Forskning\Papers\Intraday rounding problem\python\slave.py", line 71, in <module>
    main(f)
  File "b:\Forskning\Papers\Intraday rounding problem\python\slave.py", line 51, in main
    t.send(response)
  File "b:\Forskning\Papers\Intraday rounding problem\python\multi_core.py", line 137, in send
    pickle.dump(msg,w)
OSError: [Errno 22] Invalid argument
rskning\Papers\Intraday rounding problem\python\slave.py", line 29, in main
    (msg,obj) = t.receive()
  File "b:\Forskning\Papers\Intraday rounding problem\python\multi_core.py", line 153, in receive
    raise RuntimeError("""An error occured in one of the spawned sub-processes. Check the output in "slave_errors.txt' in your working directory or run without multiprocessing""")
RuntimeError: An error occured in one of the spawned sub-processes. Check the output in "slave_errors.txt' in your working directory or run without multiprocessing
